[package]

name = "pmap"
version = "0.0.4"
authors = ["Calvin Metcalf <cmetcalf@appgeo.com>"]
description = "parallel map for rust"
repository = "https://github.com/calvinmetcalf/pmap"
license = "MIT"
